print("Cleaning up!", quote = F)
rm(trainDescr)
rm(testDescr)
rm(train.merged)
rm(test.merged)
rm(machine.appendix)
rm(train.processed)
rm(test.processed)
rm(emptyRatio)
rm(test.can.substitute)
rm(train.can.substitute)
rm(train.dummy)
rm(test.dummy)